### ISSUE TITLE
Getting application logs of containers

### ISSUE THREAD

**Issue by mikehaller** [eclipse-kanto/container-management#98] opened 2022-11-29 10:32 UTC
The kanto-cm cli tool does not seem to have a convenient way to retrieve the application logs from a container yet.

Right now, the user needs to get information about the container (`kanto-cm get -n <container>`) to find out about container id. Then he needs to know the location of containerd storage of the container to find the log file there - which is a lot of internal knowledge and cumbersome to remember.

It would be nice if there would be a simple `kanto-cm logs <container>` command available in the cli which retrieves and prints out the application log.

**Comment by e-grigorov** [comment] 2022-11-30 11:49
Currently, the daemon gRPC server works more or less with so called common types. Log file transfer will require data streaming. It seems that as a first step here, we have to check how to support data streaming and what is the size impact on the daemon.

**Comment by k-gostev** [comment] 2022-12-09 08:41
In my next comment I will provide a proposal on how such task can be achieved in more technical point of view. @mikehaller I would be happy if could provide more info on what would be convenient way to you to see the container logs or basically what features you would like to be provided by the `kanto-cm logs` command. Feedback on the technical solution is also appreciated.

**Comment by k-gostev** [comment] 2022-12-09 08:41
# Kanto logging proposal

Application logs are particularly useful for debugging problems and monitoring cluster activity, so most modern applications have some kind of logging mechanism.
The easiest and most adopted logging method for containerized applications is writing to standard out and error streams. Considering this a container management system should support logging.

Eclipse Kanto Container Management already partially provides logging mechanism by defining where and how log files must be produced and rotated. What is missing is a convenient way to fetch the already
stored logs. This document proposes mechanism for this functionality. The concept is based on already adopted practices while still considers the ideas and purposes of Eclipse Kanto.

## Container logs in Eclipse Kanto

Currently Eclipse Kanto provides logging configuration per container that defines the log type and the rotation mechanism. The log configuration looks as follows:

Property|Type|Default|Description
--------|----|-------|-----------|
type|string|json-file|Type in which the logs are produced, the possible options are: json-file or none|
max_files|int|2|Maximum log files before getting rotated|
max_size|string|100M|Maximum log file size before getting rotated as a number with a unit suffix of B, K, M and G|
root_dir|string|<meta_path>/containers/<container_id>|Root directory where the container’s log messages are stored|
mode|string|blocking|Messaging delivery mode from the container to the log driver, the supported modes are: blocking and non-blocking|
max_buffer_size|string|1M|Maximum size of the buffered container’s log messages in a non-blocking mode as a number with a unit suffix of B, K, M and G|

## Logging principles for Eclipse Kanto Container Management

Eclipse Kanto Container Management is specially designed to be lightweight. The logging functionality also have to fallow that design and principles. Considering that the main purpose of a container management system is to take care of the lifecycle of containers and not monitoring their behavior it is also natural that the any logging functionality should be as simle, lightweight and reliable as possible. This means that the logging functionality of a container management system is by design insufficient 
for complete logging solution. All monitoring requirements and functionalities such as backend store services, log backups, analytic services, log queries, log transformations and so on are out of scope of the container management logging functionalities.
The container management must provide only basic mechanisms for fetching and rotating logs.

# Log client-server streaming using gRPC services - Preferred solution

## Server side implementation

Eclipse Kanto Container Management daemon is based on gRPC services that are called by the client to control the lifecycle of a container. The logging functionality should also take advantage of this approach adapting the nature of the logs to achieve lightweight and reliable transport of container logs to the client. The Container Management should define a gRPC streaming service that will transfer container logs on chunks with size not more than 4MB, which is the default gRPC message size. This approach
offers fast and reliable way of transferring data, that is also adopted by other solutions. The logging service will fetch the logs directly from the log file configured in the container logging configuration. This will achieve low memory footprint and data reliability. Combining log fetching directly from files and then streaming it trough gRPC service will provide simple, lightweight, fast and reliable solution. During the implementation the following things must be considered:

1. CPU Utilization - the CPU usage must be analyzed and reduced to minimum.
2. The Server logging service must not parse, understand or alter in any way the contents of a log file.
3. The Server logging service must only transfer the desired quantity of logs.
4. The Server logging service must be as simple as possible and its purpose is to only provide log data as fast and reliable as possible.
5. The Server logging service must not be used to transfer big logging data, blobs or anything else that can jeopardize the stability of the Eclipse Kant Container Management.
6. The `max_files` property should be removed and only one logging file must stored on the file system per container in order to comply with the best logging practices for a container management service.
7. The Server logging service enablement should be configurable

## Client side implementation

Eclipse Kanto Container Management comes with a CLI tool that calls the daemon services in order to allow the user to manage the lifecycle of a container. The CLI tool should be able to call the server logging service to fetch the logs and provide user convenient outputs. It should be implemented with simple features such as `tail`, `logs since` and so on. The client must be maximum optimized in order not to unnecessarily slowing the server.

# Log fetching directly from the CLI

The most simple way to provide some level of convenience is to provide a functionality to the container management CLI to fetch the log files directly from the file system and print them to the user without the need of client-server communication.
This option is technically less challenging and preserves the integrity of the daemon. This option requires the CLI to be on the same device as the daemon and can't be used remotely using the `--host` parameter. Also, it does not provide the possibility 
of implementing a fully functional logging solution. This approach provides just a convenient way of printing the container logs on the console.

## Client use

Both proposals will be used in the same manner by the end user and they will not be different in any way in terms of user experience. The functionality will be used by calling `kanto-cm logs <arguments> <container_id>`.

## References and further reading:
- [Kubernetes logging architecture](https://kubernetes.io/docs/concepts/cluster-administration/logging/)
- [Docker logging](https://docs.docker.com/config/containers/logging/)
- [gRPC Stream Performance](https://ably.com/blog/grpc-stream-performance)
- [Performance best practices with gRPC](https://learn.microsoft.com/en-us/aspnet/core/grpc/performance?view=aspnetcore-7.0)

**Comment by chheis** [comment] 2022-12-12 17:37
@k-gostev I like the "kanto-cm logs <arguments> <container_id>" idea. I also observed the unlikely situation as @mikehaller to cat and tail the logs from the device storage. This feature would be great for debugging on the device. Please also take into account to have the "-n" (name of container) option in place :)

**Closed** 2023-01-06 07:51 UTC
Labels: task
